### ISSUE TITLE
@Setter @Getter无效，是什么原因啊

### ISSUE THREAD

**Issue by hymbo** [jcalaz/xmarket#1]
导入as后，@Setter @Getter无效，是什么原因啊

**Comment by huaminghui** [comment]
在没有网络的情况下，点击下半部分四个选项就出现这个了Unable to add window android.view.ViewRootImpl$W@2a43b8e5 -- permission denied for this window type，

**Comment by jcalaz** [comment]
安装android studio安装lombok插件，重启android studio就可以了

**Comment by jcalaz** [comment]
我在本机运行没有事，参考下http://blog.csdn.net/yayun0516/article/details/52206587

**Comment by hymbo** [comment]
谢谢了，安装LOMBOK插件后正常运行，只是几秒钟后会崩溃退出，迟些我研究学习下，项目现在是没有数据的吗？
